### ISSUE TITLE
roadmap - 0.0.2

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#26]
### Done
- [x] port language resources from upstream
   - [x] Azerbaijan #20 
   - [x] Basque #12 
   - [x] Russian #12
- [x] multiple wake words
  - [x] feature / multiple wake words #2
  - [x] refactor / sleep mode - #10
 - [x] secure mycroft.conf #19 #22
 - [x] split gui from enclosure #8 
 - [x] support user defined skills directories #7     
 
### In Progress
- [ ] full xdg compliance #6 
  - [ ] migrate skill settings #11
- [ ] feat / skill packaging - #9
   - [ ] publish essential/core skills in pypi
       - [ ] skill setup https://github.com/OpenVoiceOS/skill-ovos-setup/pull/5
       - [ ] skill wifi https://github.com/OpenVoiceOS/skill-balena-wifi-setup/pull/2
       - [ ] skill naptime https://github.com/OpenVoiceOS/skill-naptime/pull/1
       - [ ] skill common query https://github.com/OpenVoiceOS/skill-ovos-common-query/pull/1
       - [ ] to be continued ...
   - [ ] publish default skills in pypi
       - [ ] skill weather https://github.com/OpenVoiceOS/skill-weather/pull/1
       - [ ] skill personal https://github.com/OpenVoiceOS/skill-personal/pull/1
       - [ ] skill volume https://github.com/OpenVoiceOS/skill-ovos-volume/pull/6
       - [ ] skill ovos gui https://github.com/OpenVoiceOS/skill-ovos-mycroftgui/pull/3
       - [ ] skill camera https://github.com/OpenVoiceOS/skill-camera/pull/1
       - [ ] skill ovos settings https://github.com/OpenVoiceOS/skill-ovos-settings/pull/2
       - [ ] skill homescreen https://github.com/OpenVoiceOS/skill-ovos-homescreen/pull/6
       - [ ] to be continued ...
   - [ ] deprecate msm #25
- [ ] relax requirements as much as possible
    - [x] fix MYCROFT_LOOSE_REQUIREMENTS #18
    - [x] remove inflection #17
    - [ ] remove requests_futures #14
    - [x] move to combo_lock #15
    - [x] relax pinned versions #21
- [ ] remove duplicated code
   - [x] move to ovos_utils #5
   - [ ] move to ovos plugin manager #1
       - [ ] remove tts_cache #16
- [ ] bugs and cleanup
  - [x] fix priority skills not loading #23
  - [ ] fix MycroftSkill config_core not updating #13
  - [x] feat / disable mic ipc #3
  
### TODO
- [ ] ?

What else needs to happen?
