### ISSUE TITLE
roadmap - 0.0.7

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#270]
what is needed for release 0.0.7

- [x] core
   - [x] https://github.com/OpenVoiceOS/ovos-core/pull/275
   - [x] https://github.com/OpenVoiceOS/ovos-core/pull/269
   - [x] https://github.com/OpenVoiceOS/ovos-core/issues/258
      - [x] https://github.com/OpenVoiceOS/ovos-core/pull/271  <- avoids issue above, not a fix
   - [x] https://github.com/OpenVoiceOS/ovos-core/pull/272
       - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/49
       - [x] https://github.com/OpenVoiceOS/ovos-utils/pull/96
       - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/51
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/291
    - [x] [OPM 0.0.22](https://github.com/OpenVoiceOS/ovos-plugin-manager/compare/V0.0.21...V0.0.22a8)
    - [x] [ovos_utils 0.0.30](https://github.com/OpenVoiceOS/ovos-utils/compare/V0.0.29...V0.0.30a3)
    - [x] [ovos_workshop 0.0.11](https://github.com/OpenVoiceOS/OVOS-workshop/compare/V0.0.10...V0.0.11a6)
    - [x] [ovos-ocp-audio-plugin 0.0.4](https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/compare/V0.0.3...V0.0.4a13)
      - [x] https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/pull/53
    - [x] [ovos-config 0.0.7](https://github.com/OpenVoiceOS/ovos-config/compare/V0.0.6...V0.0.7a2)
- [x] misc
    - [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/117
    - [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/124
    - [x] https://github.com/OpenVoiceOS/ovos-lingua-franca/pull/42
    - [x] https://github.com/OpenVoiceOS/ovos-backend-client/pull/29
    - [x] https://github.com/OpenVoiceOS/ovos-cli-client/pull/5
    - [x] https://github.com/OpenVoiceOS/ovos-utils/pull/99
    - [x] https://github.com/OpenVoiceOS/ovos-utils/pull/88
    - [x] https://github.com/OpenVoiceOS/ovos-utils/pull/95
    - [x] https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/pull/48
- [x] skills
    - [x] [add offline default skills to requirements list](https://github.com/OpenVoiceOS/ovos-core/pull/282)
        - [x] https://github.com/OpenVoiceOS/skill-ovos-volume
        - [x] https://github.com/OpenVoiceOS/skill-ovos-personal
        - [x] https://github.com/OpenVoiceOS/skill-ovos-naptime
        - [x] https://github.com/OpenVoiceOS/skill-ovos-date-time
        - [x] https://github.com/OpenVoiceOS/ovos-core/pull/278
        - [x] https://github.com/OpenVoiceOS/skill-ovos-fallback-unknown
        - [x] https://github.com/OpenVoiceOS/skill-ovos-stop
        - [x] https://github.com/OpenVoiceOS/skill-ovos-hello-world
        - [x] https://github.com/OpenVoiceOS/skill-ovos-filebrowser
        - [x] https://github.com/NeonGeckoCom/skill-alerts
    - [x] homescreen skill
        - [x] https://github.com/OpenVoiceOS/skill-ovos-homescreen/pull/59
        - [x] https://github.com/OpenVoiceOS/skill-ovos-homescreen/pull/70
    - [x] news skill
        - [x] ovos-ocp-news-plugin 0.0.3
        - [x] ovos-ocp-rss-plugin 0.0.2    
        - [x] more news stations
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/8
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/15
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/16
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/9
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/10
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/11
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/12
            - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/14
        - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/13
   - [x] implement new runtime requirements classproperty
       - [x] https://github.com/OpenVoiceOS/skill-ovos-setup/pull/71
       - [x] https://github.com/OpenVoiceOS/skill-ovos-weather/pull/21
       - [x] https://github.com/OpenVoiceOS/skill-ovos-wikipedia/pull/10
       - [x] https://github.com/OpenVoiceOS/skill-ovos-soundcloud/pull/4
       - [x] https://github.com/OpenVoiceOS/skill-ovos-homescreen/pull/71
       - [x] https://github.com/OpenVoiceOS/skill-ovos-ddg/pull/13
       - [x] https://github.com/OpenVoiceOS/skill-ovos-stop/pull/10
       - [x] https://github.com/OpenVoiceOS/skill-ovos-filebrowser/pull/4
       - [x] https://github.com/OpenVoiceOS/skill-ovos-fallback-chatgpt/pull/3
       - [x] https://github.com/OpenVoiceOS/skill-ovos-fallback-unknown/pull/2
       - [x] https://github.com/OpenVoiceOS/skill-ovos-wolfie/pull/11
       - [x] https://github.com/OpenVoiceOS/skill-ovos-youtube/pull/16
       - [x] https://github.com/OpenVoiceOS/skill-ovos-date-time/pull/12
       - [x] https://github.com/OpenVoiceOS/skill-ovos-youtube-music/pull/2
       - [x] https://github.com/OpenVoiceOS/skill-ovos-naptime/pull/7
       - [x] https://github.com/OpenVoiceOS/skill-ovos-news/pull/7
       - [x] https://github.com/OpenVoiceOS/skill-ovos-date-time/pull/13
       - [x] https://github.com/OpenVoiceOS/skill-ovos-hello-world/pull/1
       - [x] https://github.com/OpenVoiceOS/skill-homescreen-lite/pull/4
       - [x] https://github.com/NeonGeckoCom/skill-alerts/pull/73
       - [x] https://github.com/OpenVoiceOS/skill-ovos-camera/pull/8
       - [x] https://github.com/OpenVoiceOS/skill-ovos-bandcamp/pull/2
       - [x] https://github.com/OpenVoiceOS/skill-ovos-somafm/pull/2
       - [x] https://github.com/OpenVoiceOS/skill-ovos-personal/pull/5
       - [x] https://github.com/OpenVoiceOS/skill-ovos-volume/pull/18
       
nice to have:

- [ ] https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/issues/43
- [ ] https://github.com/OpenVoiceOS/skill-ovos-filebrowser/pull/3
- [ ] https://github.com/OpenVoiceOS/ovos-PHAL/pull/12
    - [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/118
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-ipgeo/pull/6
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-dashboard/pull/8
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wifi-setup/pull/19
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-gui-network-client/pull/13
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-color-scheme-manager/pull/4
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-connectivity-events/pull/8
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-mk1/pull/1
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-oauth/pull/6
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-system/pull/14

**Comment by AIIX** [comment]
Marking this issue here, was shared on the development matrix channel and making this a formal issue that causes breakage for distributions packaging ovos-core https://github.com/OpenVoiceOS/ovos-core/issues/276

**Comment by NeonDaniel** [comment]
@JarbasAl [personal skill](https://github.com/OpenVoiceOS/skill-ovos-personal/actions/runs/4139213043/jobs/7156537068) looks like it needs a token added to secrets

**Comment by NeonDaniel** [comment]
Pending Skills PRs:
- https://github.com/OpenVoiceOS/skill-ovos-date-time/pull/16
- https://github.com/OpenVoiceOS/skill-ovos-personal/pull/6
- https://github.com/OpenVoiceOS/skill-ovos-naptime/pull/9

**Comment by NeonDaniel** [comment]
Ready for stable releases:
https://github.com/OpenVoiceOS/skill-ovos-stop/compare/V0.2.0...V0.2.1a2
https://github.com/OpenVoiceOS/skill-ovos-date-time

Dependency updates to prep stable releases:
https://github.com/OpenVoiceOS/skill-ovos-personal/pull/7
https://github.com/OpenVoiceOS/skill-ovos-naptime/pull/10
https://github.com/OpenVoiceOS/skill-ovos-hello-world/pull/3
https://github.com/OpenVoiceOS/skill-ovos-filebrowser/pull/6

**Comment by NeonDaniel** [comment]
Remaining alpha dependencies:
https://github.com/OpenVoiceOS/ovos-stt-plugin-selene
https://github.com/OpenVoiceOS/skill-ovos-filebrowser
https://github.com/OpenVoiceOS/skill-ovos-hello-world
https://github.com/OpenVoiceOS/skill-ovos-date-time
https://github.com/OpenVoiceOS/skill-ovos-naptime
https://github.com/OpenVoiceOS/skill-ovos-personal
