### ISSUE TITLE
roadmap - 0.0.8

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#274]
documentation:
- [x] spec of bus messages https://github.com/OpenVoiceOS/message_spec
- [x] session
- [x] audio/utterance/metadata transformers
- [x] pipeline config
- [x] solver plugins
- [x] standalone [skill launcher](https://github.com/OpenVoiceOS/OVOS-workshop/blob/dev/ovos_workshop/skill_launcher.py#L649)
- [x] ovos-docker https://openvoiceos.github.io/ovos-docker/
- [ ] https://github.com/OpenVoiceOS/community-docs/issues/36
- [x] OpenVoiceOS/ovos-technical-manual#16

unittests:
- [x] OpenVoiceOS/ovos-core#415
- [ ] move to shared actions https://github.com/OpenVoiceOS/.github/pull/5
- [x] fix codecov automations
 - [x] unittests for session lifecycle  
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/355
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/356
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/357
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/358
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/359
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/360
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/361
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/362
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/363
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/366
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/373
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/374

audio:
- [x] move all audio output handling to ovos-audio
	- [x] https://github.com/OpenVoiceOS/ovos-audio/pull/25
	- [x] https://github.com/OpenVoiceOS/ovos-utils/pull/190
	- [x] https://github.com/OpenVoiceOS/ovos-core/pull/345
	- [x] https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/60
	- [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/129
	- [x] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-alsa/pull/20
	- [x] https://github.com/OpenVoiceOS/ovos-audio/pull/34
	
core:
- [x] https://github.com/OpenVoiceOS/ovos-core/issues/417
- [x] https://github.com/OpenVoiceOS/ovos-core/pull/163
     - [x] ovos-dinkum-listener support
- [x] session implementation
    - [x] initial implementation https://github.com/OpenVoiceOS/ovos-bus-client/blob/dev/ovos_bus_client/session.py
        - [x] https://github.com/OpenVoiceOS/ovos-core/pull/300
        - [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/136
	    - [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/20
	    - [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/10
	    - [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/8
	- [x] https://github.com/OpenVoiceOS/ovos-core/pull/160
        - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/68
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/308
       - [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/19  
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/354 
       - [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/50
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/352   
    - [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/47
        - [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/48
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/329    
    - [x] "stop" per session / active skills https://github.com/OpenVoiceOS/ovos-core/pull/391
	    - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/169
	    - [x] https://github.com/OpenVoiceOS/ovos-config/pull/94
    - [x] session support for scheduled events https://github.com/OpenVoiceOS/ovos-utils/pull/196
- [x] become a skill loader / intent framework only
    - [x] provide `ovos-core` and `mycroft` modules, deprecate `mycroft`in 0.2.0 https://github.com/OpenVoiceOS/ovos-core/pull/313
    - [x] only place where `mycroft` is imported, skills should only import ovos-workshop/ovos-utils
        - [x] standalone skill launcher
	    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/307
	    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/306
	       - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/65
	       - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/73
	       - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/76
	       - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/75
	     - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/70
	     - [x] https://github.com/OpenVoiceOS/ovos-core/pull/309
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/305
       - [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/63
    - [x] https://github.com/OpenVoiceOS/ovos-core/pull/292
        - [x] https://github.com/OpenVoiceOS/ovos-core/issues/264
        - [x] wrap all submodule packages for backwards compat until release 0.2.0
        - [x] log deprecation warnings starting on release 0.0.8
        - [x] `mycroft.gui` -> `ovos-gui`
        - [x] `mycroft.listener` -> `ovos-listener` https://github.com/OpenVoiceOS/ovos-core/pull/303
        - [x] `mycroft.audio` -> `ovos-audio` https://github.com/OpenVoiceOS/ovos-core/pull/304
        - [x] `mycroft.messagebus.service` -> `ovos-messagebus`
        - [x] `mycroft.metrics` -> `ovos-backend-client.metrics`
        - [x] move mycroft.conf from ovos-core to ovos-config
        - [x] move remaining utils under `mycroft.util` either to `ovos_utils` (or more appropriate package) or `mycroft.deprecated`
- [x] https://github.com/OpenVoiceOS/ovos-listener/issues/17
- [x] https://github.com/OpenVoiceOS/ovos-core/pull/232
- [x] bump version for https://github.com/Uberi/speech_recognition

GUI:
- [x] https://github.com/OpenVoiceOS/ovos-gui/pull/9
- [x] https://github.com/MycroftAI/mycroft-gui/pull/124
- [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/50
- [x] https://github.com/OpenVoiceOS/ovos-gui/pull/1
- [x] https://github.com/OpenVoiceOS/ovos-gui/pull/25

docker:
- [x] https://github.com/OpenVoiceOS/ovos-docker

opm:
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/140
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/141
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/17
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/131
- [x] https://github.com/OpenVoiceOS/ovos-ww-plugin-pocketsphinx/pull/4
- [x] https://github.com/OpenVoiceOS/ovos-stt-plugin-pocketsphinx/pull/3
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/139
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/151
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/147
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/148
   - [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/149

misc:
- [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/72
- [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/74

**Comment by AIIX** [comment]
- I reserve my doubts on https://github.com/OpenVoiceOS/ovos-gui/pull/1 and totally moving the GUI protocol out of ovos-core, this is needs formal discussions and what it means for GUI in the future under OVOS as a project.

**Comment by AIIX** [comment]
https://github.com/OpenVoiceOS/OVOS-workshop/pull/50 which is linked to https://github.com/OpenVoiceOS/ovos-shell/issues/29 < This needs more understanding and a better solution so I would suggest everyone else and including the community to participate, if KDE can't solve this I don't think OVOS can either, QT and GUI Frameworks are interlinked, and how QML works neither KDE nor I control it. Trying to force a implementation that is dependent on another paradigm is just going to end up causing more pain and troubles to maintain in the end.

**Comment by NeonDaniel** [comment]
I'd propose also cleaning up unused imports in dependencies and bumping those releases for this core release too.

**Comment by NeonDaniel** [comment]
ovos-workshop (0.0.12) Stable Release
- [ ] Validate ovos-gui Docker file upload/display
- [ ] Validate OCP GUI file upload/display
- [ ] Validate ovos-core latest alpha releases function as expected
- [ ] Stable ovos-utils release (0.0.35)

**Comment by NeonDaniel** [comment]
Couple alpha dependencies to push:
https://github.com/OpenVoiceOS/ovos-core/blob/b8404ca9d1f278992f5f2963d5748d933c6ffb5d/requirements/requirements.txt#L12

https://github.com/OpenVoiceOS/ovos-core/blob/b8404ca9d1f278992f5f2963d5748d933c6ffb5d/requirements/requirements.txt#L18

We should also consider pushing [mycroft backwards-compat dependencies](https://github.com/OpenVoiceOS/ovos-core/blob/testing/requirements/mycroft.txt) and [essential skills](https://github.com/OpenVoiceOS/ovos-core/blob/testing/requirements/skills-essential.txt)

**Comment by JarbasAl** [comment]
essential skills pending PR https://github.com/OpenVoiceOS/ovos-core/pull/401

**Comment by JarbasAl** [comment]
ovos-config needs further changes, to restore adapt med/low conf levels to old behaviour, as discussed with @emphasize in chat today
