### ISSUE TITLE
roadmap - 0.0.9

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#281]
depends on
- [ ] https://github.com/OpenVoiceOS/ovos-core/issues/274

what is needed for release 0.0.9

GUI:
- [ ] https://github.com/OpenVoiceOS/ovos-gui/pull/26
- [ ] https://github.com/OpenVoiceOS/ovos-shell/issues/29

Pipelines:
- [x] introduce the concept of intent pipeline https://github.com/OpenVoiceOS/ovos-core/pull/336
- [ ] PipelinePlugin base class - https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/177
- [ ] standardize bus api for intent service https://github.com/OpenVoiceOS/ovos-utils/pull/193
- [ ] migrate skills to new intent service api https://github.com/OpenVoiceOS/OVOS-workshop/pull/132
- [ ] [persona pipeline](https://github.com/OpenVoiceOS/ovos-persona) plugin
- [x] allow persona to select pipeline matchers (via Session) https://github.com/OpenVoiceOS/ovos-core/pull/352
- [ ] new pipeline plugin https://github.com/OpenVoiceOS/ovos-core/issues/273
    - [ ] new pipeline plugin, use LLM to select final intent to trigger

Intent Matching:
- [ ]  https://github.com/OpenVoiceOS/OVOS-workshop/pull/12
- [ ] new pipeline plugin https://github.com/OpenVoiceOS/ovos-core/pull/310
- [ ] https://github.com/OpenVoiceOS/ovos-core/issues/376

OCP:
- [ ] https://github.com/OpenVoiceOS/ovos-media/issues/15
- [ ] https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/pull/58
- [ ] https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/issues/43

Persona:
- [ ] https://github.com/OpenVoiceOS/ovos-persona/issues/4

[CommonIOT](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-commonIOT):
- [ ] [VUI](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-commonIOT/blob/dev/ovos_PHAL_plugin_commonIOT/vui.py)
- [ ] [bus api](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-commonIOT/blob/dev/ovos_PHAL_plugin_commonIOT/device_manager.py)
- [ ] [GUI](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-commonIOT/blob/dev/ovos_PHAL_plugin_commonIOT/gui.py) (migrated from HA PHAL plugin) 
- [ ] [reference plugins](https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/97)
    - [ ] migrate HA phal plugin to a IOT plugin
    - [ ] https://github.com/OpenVoiceOS/ovos-iot-plugin-lan
    - [ ] https://github.com/OpenVoiceOS/ovos-iot-plugin-kasa
    - [ ] https://github.com/OpenVoiceOS/ovos-iot-plugin-bluetooth
 - [ ] expose ovos itself to other IOT frameworks https://github.com/OpenVoiceOS/ovos-PHAL-sensors
        
PHAL:
- [ ] https://github.com/OpenVoiceOS/ovos-PHAL/pull/12
    - [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/118
    - [x] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-ipgeo/pull/6
    - [x] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wifi-setup/pull/19
    - [x] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-connectivity-events/pull/8
    - [ ] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-mk1/pull/1
    - [x] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-oauth/pull/6
    - [x] https://github.com/OpenVoiceOS/ovos-PHAL-plugin-system/pull/14
      
Backend:
- [ ] https://github.com/OpenVoiceOS/ovos-backend-client/pull/11
