### ISSUE TITLE
Copyleft detected - list of deps & util to detect them

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#51]
All OVOS repos intend to be "universal donors",  it should be possible to use every ovos repo without dragging a viral package

A [new util](https://github.com/NeonJarbas/lichecker/blob/master/lichecker/__init__.py#L113) i wrote revealed some problems with GPL dependencies that are incompatible

Additionally and just to be on safe side we also want to avoid LGPL due to reasons discussed [elsewhere](https://softwareengineering.stackexchange.com/questions/119436/what-does-gpl-with-classpath-exception-mean-in-practice/326325#326325)

viral packages in mycroft/ovos-core
```
'fann2': 'LGPL',
'chardet': 'LGPL',
'unidecode': 'GPL',
`python-vlc`: `LGPL`.
'pyxdg': 'GPL-2.0'
```

additional viral packages in ovos_workshop / OCP
```
'mutagen': 'GPL-2.0-or-later'
```

tagging @krisgesling because this is also a concern for mycroft

# TODO list

- [x] `python-vlc` is already optional
- [x] `fann2` is required for padatious, but padatious is already optional in ovos-core (not mycroft)
- [x] bump `requests` to [>= 2.26.0](https://github.com/psf/requests/pull/5797) in every package we own to remove `chardet`
   - progress tracked in https://github.com/OpenVoiceOS/ovos-core/pull/52
- [x] replace `pyxdg` in every package we own, i suggest https://github.com/srstevenson/xdg
    - [x] ovos-core https://github.com/OpenVoiceOS/ovos-core/pull/53
    - [x] ovos_utils https://github.com/OpenVoiceOS/ovos_utils/pull/21
    - [x] ovos plugin manager https://github.com/OpenVoiceOS/OVOS-plugin-manager/pull/30
    - [x] ovos precise lite plugin https://github.com/OpenVoiceOS/ovos-ww-plugin-precise-lite/pull/1
    - [x] ovos precise plugin
    - [x] ovos mimic plugin
    - [ ] ....
    - [x] json_database https://github.com/OpenJarbas/json_database/pull/1
- [x] default to `youtube-dl` instead of `yt-dlp` to remove `mutagen`from OCP dragged dependencies, 
    - alternatively don't install `youtube-dl`or `yt-dlp` at all it is optional already. skills that need it should list it in requirements.txt and request it directly anyway
    - solved by https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/commit/4162aaecab5c34dd73d0659747fcbd5d8b173b0b and https://github.com/OpenVoiceOS/OVOS-workshop/commit/01d68c774ca6faa2846623152e818b18dd46ec47
- [x] `unidecode` comes from phoneme_guesser, it is unused but pinned in some plugins to workaround an old bug, should also be removed from phoneme_guesser directly

**Comment by JarbasAl** [comment]
added a github workflow to ensure this doesn't happen again, see https://github.com/NeonJarbas/ovos-core/actions/runs/1842592706 and https://github.com/OpenVoiceOS/ovos-core/pull/53

**Comment by NeonDaniel** [comment]
I don't think it's necessarily problematic to interface with GPL dependencies if we are not contributing to those packages. That said, it is nice to support permissively licensed projects and not support restrictively licensed ones

**Comment by JarbasAl** [comment]
still some packages to go, detected in #56

**Comment by JarbasAl** [comment]
all tests passing now :tada:

**Comment by ChanceNCounter** [comment]
@NeonDaniel the applicability of language that distinguishes linked works from derivative works is ambiguous all over the copyleft world, and the only way to be certain our interpreted code is nonderivative, short of becoming the test case, is to avoid copyleft (*especially* the LGPL)

Stallman tried twice to account for libraries, blew it twice for interpreters, and refuses to address the problem. When you ask the FSF to clarify the classpath or linking exceptions wrt Python, they helpfully clarify, "You must comply with the terms of the license."

It needs to be acknowledged that someone who would, with a grin, say, "It's not a virus, it's a spider plant," fully aware that the latter is a destructive, invasive species impossible to expunge from your land, is a hostile person.
